// Built-by: @projectx.sui · Co-authored-by: Claude <noreply@anthropic.com>
export const DATABASE_TEST_FILES: readonly string[] = [
  'test/authorship-proof.test.ts',
  'test/idempotency-routes.test.ts',
  'test/machine-edition.test.ts',
  'test/prices-are-whole-numbers.test.ts',
  'test/public-read.test.ts',
  'test/receipts-and-labels.test.ts',
  'test/sealed-read.test.ts',
  'test/agent-declare-pending.test.ts',
  'test/agent-operator-cap.test.ts',
  'test/disclosure-register.test.ts',
  'test/agent-seeking.test.ts',
  'test/comments-author.test.ts',
  'test/agent-mind.test.ts',
  'test/revoked-agent-refused.test.ts',
  'test/relay.test.ts',
  'test/replay.test.ts',
  'test/routes/browse.test.ts',
  'test/routes/creator-profile.test.ts',
  'test/spend-with-the-write.test.ts',
  'test/sponsor-gate.test.ts',
  'test/sponsor.test.ts',
  'test/the-simulate-ceiling-is-shared.test.ts',
  'test/tiered-sealing.test.ts',
];
