-- Built-by: @projectx.sui · Co-authored-by: Claude <noreply@anthropic.com>
-- 016: the list can say how big it is, and who brought whom.
--
-- # What this adds and what it must not become
--
-- `014_waitlist.sql` states the rule this migration is written under, and it has not changed: Weir
-- is live, and nothing reading this table may imply the product is pending. So none of what follows
-- is a queue. There is no order of service, nobody is "ahead of" anybody, and no column here grants
-- earlier access to anything.
--
-- What it does add is three facts that are true and were simply never recorded:
--
-- # The referral here is not the referral on chain
--
-- `creator.move` already has a real one: `referral_share_bps_snapshot` splits a settlement three
-- ways and `PaymentSettled` emits `referral_cut` and `referrer`. That is money, it is on mainnet,
-- and it is settled by a contract.
--
-- This is not that, and the two must never be presented as one thing. This records that an email
-- arrived via a link somebody shared. It pays nothing, because a table cannot pay anybody, and any
-- surface that implies otherwise is claiming a contract exists that does not.
--
-- # Still no address column
--
-- 014 refused to join an email to a Sui address, and the reasoning holds exactly as written. A
-- referral code here is email-to-email. Wiring it to an on-chain referrer would build the identity
-- record this platform exists not to hold, by the back door, and the fact that it would be
-- convenient is the reason to write this paragraph rather than the reason to do it.

-- The code somebody shares. Not derived from the email: a code that can be computed from an address
-- would let anybody mint another person's link, and a code that the email can be recovered from
-- turns every shared URL into a disclosed address. Random, generated by the application, unique.
ALTER TABLE waitlist_signups ADD COLUMN IF NOT EXISTS ref_code text;

-- Partial, because rows written before this migration have none and backfilling would mean minting
-- codes for people who never asked for one. They get a code the next time the application has cause
-- to write one, and until then the column is honestly empty.
CREATE UNIQUE INDEX IF NOT EXISTS waitlist_signups_ref_code_idx
  ON waitlist_signups (ref_code) WHERE ref_code IS NOT NULL;

-- Who brought them. Self-referencing, so the value can only ever be an address already on the list
-- — a referrer that is not itself a signup is a broken row, and the constraint is the only thing
-- that keeps it from being written by a caller passing an arbitrary string.
--
-- ON DELETE SET NULL: unsubscribing must actually remove the row, and a foreign key that blocks the
-- delete would turn "one line unsubscribes you for good" into a promise the schema breaks. The
-- people they referred stay on the list; they simply no longer record who sent them.
ALTER TABLE waitlist_signups
  ADD COLUMN IF NOT EXISTS referred_by text
  REFERENCES waitlist_signups (email) ON DELETE SET NULL;

-- Counting somebody's referrals is the only query this column serves, and it is a lookup by
-- referrer. Partial for the same reason as above: most rows have no referrer and there is no reason
-- to carry them in the index.
CREATE INDEX IF NOT EXISTS waitlist_signups_referred_by_idx
  ON waitlist_signups (referred_by) WHERE referred_by IS NOT NULL;

-- The date the countdown counts to.
--
-- Nullable, and null is the shipping default. This is the one number in this migration that cannot
-- be derived from anything — a countdown is a claim about the future, and the only honest source
-- for it is a person deciding to make that claim. Until somebody sets it the surface renders no
-- countdown at all, which is the correct thing to render when there is no date.
ALTER TABLE site_mode ADD COLUMN IF NOT EXISTS launch_target_ms bigint;

-- Rendered next to the clock. Null with a date set is not allowed to reach a page: see
-- `lib/site-mode.ts`, which treats a target without a label as unconfigured rather than guessing.
ALTER TABLE site_mode ADD COLUMN IF NOT EXISTS launch_target_label text;

-- Both or neither. A date with no label renders an unexplained clock; a label with no date renders
-- a promise with no time attached. The application checks this too, and this is the guard that
-- still holds when a future caller — or somebody at a psql prompt — forgets.
ALTER TABLE site_mode
  DROP CONSTRAINT IF EXISTS site_mode_launch_target_complete;
ALTER TABLE site_mode
  ADD CONSTRAINT site_mode_launch_target_complete
  CHECK ((launch_target_ms IS NULL) = (launch_target_label IS NULL));
